version: 0.2

phases:
    install:
        commands:
            - pip install --upgrade pip
            - pip install virtualenv
            - make env
    build:
        commands:
            - make
            - make clean
artifacts:
    files:
        - appspec.yaml
