version: 0.2

phases:
    install:
        commands:
            - pip install --upgrade pip
            - pip install virtualenv
            - make env
    build:
        commands:
            - make
            - make clean


artifacts:
    files:
        - '**/*'
    secondary-artifacts:
        BuildArtifact:
            base-directory: $CODEBUILD_SRC_DIR/
            files:
                - '**/*'
        WebArtifact:
            base-directory: $CODEBUILD_SRC_DIR/web
            files:
                - index.html
