version: 0.2

phases:
    install:
        commands:
            - pip install --upgrade pip
            - pip install virtualenv
            - apt install nodejs npm
            - npm install -g serverless
            - make env
    build:
        commands:
            - make
            - make clean
    post_build:
        commands:
            - make deploy
